### ISSUE TITLE
bridge_troll sometimes gets in a bad mood on Heroku and stops processing requests

### ISSUE THREAD

**Issue by tjgrathwell** [railsbridge/bridge_troll#371]
The heroku dashboard looks like this (times in UTC):

![screen shot 2015-09-05 at 11 26 00 am](https://cloud.githubusercontent.com/assets/1041691/9700688/f9817668-53c0-11e5-8530-ca920359b0d7.png)

New Relic looks like this (times in PST):

### Last 24 hr
![screen shot 2015-09-05 at 11 29 45 am](https://cloud.githubusercontent.com/assets/1041691/9700701/c5ed729c-53c1-11e5-9146-1f496d94ac67.png)

### Last 6 hr
![screen shot 2015-09-05 at 11 30 35 am](https://cloud.githubusercontent.com/assets/1041691/9700702/cae7ca54-53c1-11e5-9f0a-f1e08bec4295.png)

I have no idea what triggered the giant spike that New Relic says happened in "Middleware". It was at 11:30PM, maybe an automated dyno restart?

When I last saw issues like this I installed the Rack::Timeout gem with the hope that when these timeouts started happening they would trigger exceptions showing a cause. So far, it has not. There's a new release of Rack::Timeout recently though, maybe it's better?

It's possible using one of the paid new relic addons would give more information, we don't know how long the SQL queries are taking for example.

**Comment by tjgrathwell** [comment]
As an additional step, in 9c803084beb0b00be1e0bd17a516507e0f054b98 I've changed the `all_events.json` feed that railsbridge.org uses to fetch events from Bridgetroll.

railsbridge.org had been pulling the entire events feed (which is getting more and more expensive to generate) and sorting through the json on the other side. Now there's a `/events.json?type=upcoming`, which is less expensive for everyone in situations where only upcoming events are desired.

New Relic said `all_events.json` was the request taking the most "wall clock time", so now that it's been reduced maybe some other pathological / thread-jamming request will reveal itself.

**Comment by tjgrathwell** [comment]
I figured out how to keep the app working but the answer is somewhat unsatisfying!

Near as I can tell, whenever the app starts up there is some race condition whereby one (or both?) of the dynos might wedge in some confusing way. This causes any traffic routed to them to time out and die. Rack::Timeout is absolutely no help, you can watch the requests stall out in the log but it doesn't generate an exception or any other useful thing. It looks like this:

```
ac37-e9bc9a2bbe0d wait=22ms timeout=25000ms service=24004ms state=active
2015-09-06T11:35:38.706746+00:00 app[web.1]: source=rack-timeout id=671ce39b-6a84-4d73-ac37-e9bc9a2bbe0d wait=22ms timeout=25000ms service=25004ms state=active
2015-09-06T11:35:38.706894+00:00 app[web.1]: source=rack-timeout id=671ce39b-6a84-4d73-ac37-e9bc9a2bbe0d wait=22ms timeout=25000ms service=25004ms state=timed_out
```

Interestingly, during boot the app produces these other thready warnings, though it seems to do so regardless of whether the process ultimately ends up wedged:

```
2015-09-06T11:34:44.467235+00:00 app[web.2]: [3] ! WARNING: Detected 2 Thread(s) started in app boot:
2015-09-06T11:34:44.467329+00:00 app[web.2]: [3] ! #<Thread:0x007f6bfb4a47c8@/app/vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/threading/agent_thread.rb:12 sleep> - /app/vendor/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:93:in `join'
2015-09-06T11:34:44.467354+00:00 app[web.2]: [3] ! #<Thread:0x007f6bfb3b8dc8@/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:80 sleep> - /app/vendor/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:82:in `sleep'
```

Various github issues on the internet say these can be ignored.

The most complicated part of the puma startup process seems to be `preload_app!`, which loads all your code in a parent process that forks off in to N other worker processes. The parent process ultimately dies, and work like connecting to the DB is re-done in the child process. It's possible that either:
* the parent is consuming some resource what needs to be reclaimed, OR
* some initialization is running multiple times that never expected to

I don't know the exact mechanism by which `preload_app!` ruins everything, but our Heroku dynos currently only use 1 worker each (trying for 2 blew past the memory limit) so it isn't gaining anything.

Normally, I could get the app to wedge by doing a `heroku restart` 5-10 times, but I haven't seen it wedge with `preload_app!` removed (62450d2904814c2393550eb9f3100ee1bbc3cc2f), so I'm calling this solved for now.
