### ISSUE TITLE
This page can't load Google Maps correctly.

### ISSUE THREAD

**Issue by imanialexis** [railsbridge/bridge_troll#599]
On the page for the Fall 2018 Workshop (events/450) google maps is not loading

**Comment by wassimk** [comment]
I'm happy to work on this. Someone needs to generate a new Google API key, I believe the problem is it's not free anymore.

**Comment by jhsu802701** [comment]
When I run the test suite, I get the following test failure:
```
  1) organization pages organization index shows a map of events with their last event
     Failure/Error: raise klass.new(json['error'])
     
     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
     
       You have exceeded your request quota for this API. See https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors
       You have exceeded your request quota for this API. See https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors
           at http://maps.google.com/maps/api/js?v=3.18&sensor=false&libraries=geometry:66 in Jc
       You have exceeded your request quota for this API. See https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors
       You have exceeded your request quota for this API. See https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors
           at http://maps.google.com/maps/api/js?v=3.18&sensor=false&libraries=geometry:66 in Jc
     # /home/winner/.rbenv/gems/2.5.0/gems/poltergeist-1.14.0/lib/capybara/poltergeist/browser.rb:376:in `command'
     # /home/winner/.rbenv/gems/2.5.0/gems/poltergeist-1.14.0/lib/capybara/poltergeist/browser.rb:39:in `current_url'
     # /home/winner/.rbenv/gems/2.5.0/gems/poltergeist-1.14.0/lib/capybara/poltergeist/driver.rb:101:in `current_url'
     # /home/winner/.rbenv/gems/2.5.0/gems/capybara-2.13.0/lib/capybara/session.rb:202:in `current_url'
     # /home/winner/.rbenv/gems/2.5.0/gems/capybara-screenshot-1.0.14/lib/capybara-screenshot/rspec.rb:55:in `block in after_failed_example'
     # /home/winner/.rbenv/gems/2.5.0/gems/capybara-2.13.0/lib/capybara.rb:357:in `using_session'
     # /home/winner/.rbenv/gems/2.5.0/gems/capybara-screenshot-1.0.14/lib/capybara-screenshot/rspec.rb:54:in `after_failed_example'
     # /home/winner/.rbenv/gems/2.5.0/gems/capybara-screenshot-1.0.14/lib/capybara-screenshot/rspec.rb:84:in `block (2 levels) in <top (required)>'
```

**Comment by ultrasaurus** [comment]
what do you think about replacing with alternate visualization?  I made this a while back:  https://bridgefoundry.org/workshop-map/  -- not sure if data source is dynamic, but might be straightforward to make it so

**Comment by ultrasaurus** [comment]
FYI -- if people love the google maps, I can register for the API. Even if it costs $, my guess will be low for our traffic.  

Personally I have found the Google Map UI to be fairly unreadable and I always accidentally zoom out and get multiple copies of the world, which is pretty weird.  Tho I dunno if that just me.  

What do other folks think?

**Comment by ultrasaurus** [comment]
ah, I didn't read the issue carefully, and just realized this happens on the event detail page -- which seems pretty important to fix!

![image](https://user-images.githubusercontent.com/41906/51782129-5144d100-20d8-11e9-8a1f-75715a661242.png)

I will see if I have credentials tomorrow -- or just make a new key.  I set up Firebase Hosting a while back to add SSL for bridgefoundry.org website, so we can generate a new key from that account if I can't find the RailsBridge one.

**Comment by ultrasaurus** [comment]
@rachelober has volunteered to dig into the code to figure out where the API Key is referenced, then pair with me on deploying it (since I would expect it's in an environment variable or something)

If anyone knows offhand info about this, please feel free to chime in!

**Comment by tjgrathwell** [comment]
At the time the maps were originally implemented, Google didn't require an API key at all for simple map functionality. Looks like the change happened in June 2018: https://developers.google.com/maps/billing/important-updates#api_keys_are_now_required

the map code in question should be here:
https://github.com/railsbridge/bridge_troll/blob/b77829a53106b89807f7ded1d3b9d275bbefd014/app/views/shared/_map.html.erb

From the gmaps4rails docs, [the way to provide your key is to add a key=... param when loading the JS](https://github.com/apneadiving/Google-Maps-for-Rails#requirements)

Since the functionality we're using is pretty limited and the site doesn't get a huge amount of traffic, the costs will be either $0 or otherwise shouldn't exceed the $200 credit. But someone still needs to add billing info to a google account and get the API key. Hopefully some sort of organizational account rather than an individual.

**Comment by ultrasaurus** [comment]
WIP - https://github.com/railsbridge/bridge_troll/pull/610
