### ISSUE TITLE
flakey test?  intermittent "false positive" failures on travis-ci

### ISSUE THREAD

**Issue by ultrasaurus** [railsbridge/bridge_troll#792]
example: https://travis-ci.org/railsbridge/bridge_troll/jobs/596522198

Many errors like stacktrace below:

```
Failures:
  1) Announcing an event automatically after approval will not allow the announcement to be resent by an organizer
     Got 0 failures and 3 other errors:
     1.1) Failure/Error: visit '/'
          
          EOFError:
            end of file reached
          # ./spec/features/events/organizer/announcing_an_event_request_spec.rb:44:in `block (4 levels) in <top (required)>'
     1.2) Failure/Error:
            raise e, "Failed to open TCP connection to " +
              "#{conn_address}:#{conn_port} (#{e.message})"
          
          Errno::ECONNREFUSED:
            Failed to open TCP connection to 127.0.0.1:9515 (Connection refused - connect(2) for "127.0.0.1" port 9515)
          # /home/travis/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect'
          # /home/travis/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/net/http.rb:946:in `block in connect'
          # /home/travis/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/timeout.rb:76:in `timeout'
          # /home/travis/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/net/http.rb:945:in `connect'
          # /home/travis/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/webmock-3.7.6/lib/webmock/http_lib_adapters/net_http.rb:136:in `start_with_connect_without_finish'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/webmock-3.7.6/lib/webmock/http_lib_adapters/net_http.rb:104:in `request'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/remote/http/default.rb:129:in `response_for'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/remote/http/default.rb:82:in `request'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in `execute'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/remote/w3c/bridge.rb:108:in `url'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/common/driver.rb:140:in `current_url'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/capybara-3.29.0/lib/capybara/selenium/driver.rb:92:in `current_url'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/capybara-3.29.0/lib/capybara/session.rb:227:in `current_url'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/capybara-screenshot-1.0.23/lib/capybara-screenshot/rspec.rb:56:in `block in after_failed_example'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/capybara-3.29.0/lib/capybara.rb:365:in `using_session'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/capybara-screenshot-1.0.23/lib/capybara-screenshot/capybara.rb:7:in `using_session'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/capybara-screenshot-1.0.23/lib/capybara-screenshot/rspec.rb:55:in `after_failed_example'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/capybara-screenshot-1.0.23/lib/capybara-screenshot/rspec.rb:97:in `block (2 levels) in <top (required)>'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:450:in `instance_exec'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:450:in `instance_exec'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:363:in `run'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:515:in `block in run_owned_hooks_for'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:514:in `each'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:514:in `run_owned_hooks_for'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:601:in `block in run_example_hooks_for'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:600:in `each'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:600:in `run_example_hooks_for'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:471:in `run'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:510:in `run_after_example'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:276:in `block in run'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:472:in `block in run'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:612:in `block in run_around_example_hooks_for'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:345:in `call'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-rails-3.9.0/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:450:in `instance_exec'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:450:in `instance_exec'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:381:in `execute_with'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:614:in `block (2 levels) in run_around_example_hooks_for'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:345:in `call'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:615:in `run_around_example_hooks_for'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:472:in `run'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:254:in `run'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:633:in `block in run_examples'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:629:in `map'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:629:in `run_examples'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:595:in `run'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:596:in `block in run'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:596:in `map'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:596:in `run'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:596:in `block in run'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:596:in `map'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:596:in `run'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/runner.rb:121:in `map'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/configuration.rb:2031:in `with_suite_hooks'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/reporter.rb:74:in `report'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/runner.rb:115:in `run_specs'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/runner.rb:89:in `run'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/runner.rb:71:in `run'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/lib/rspec/core/runner.rb:45:in `invoke'
          # /home/travis/build/railsbridge/bridge_troll/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.9.0/exe/rspec:4:in `<top (required)>'
          # bin/rspec:8:in `load'
          # bin/rspec:8:in `<main>'
          # 
          #   Showing full backtrace because every line was filtered out.
          #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
          #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
          # ------------------
          # --- Caused by: ---
          # Errno::ECONNREFUSED:
          #   Connection refused - connect(2) for "127.0.0.1" port 9515
          #   /home/travis/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/net/http.rb:947:in `initialize'
```

**Comment by michaelglass** [comment]
I believe what's happening here is chromedriver is intermittently failing to start.

**Comment by ultrasaurus** [comment]
https://travis-ci.org/railsbridge/bridge_troll/jobs/597508944 (from https://github.com/railsbridge/bridge_troll/pull/793)
```
which chromedriver
/home/travis/build/railsbridge/bridge_troll/node_modules/.bin/chromedriver
chromedriver --version
ChromeDriver 77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442})
```

**Comment by michaelglass** [comment]
this seems to have resolved itself with a chromedriver upgrade to 76
